name: Starburst CI Pipeline

on:
  push:
    branches: [main]

jobs:
  run-query:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install Trino CLI
        run: |
          wget https://repo1.maven.org/maven2/io/trino/trino-cli/418/trino-cli-418-executable.jar
          mv trino-cli-418-executable.jar trino
          chmod +x trino

     - name: Run Query on Starburst Galaxy
  run: |
    ./trino \
    --server https://yourdurgesh-free-cluster.trino.galaxy.starburst.io:443 \
    --user "${{ secrets.SB_USER }}" \
    --catalog tpch \
    --schema tiny \
    --access-token "${{ secrets.SB_PASSWORD }}" \
    --execute "SELECT 1"
